---

ansible_groups: {}

ansible_playbooks:
  - 'testing_deployment.yml'

vagrant_provider: 'virtualbox'
vagrant_synced_folder_type: 'virtualbox'

vagrant_servers:
  - name: 'fail2ban-trusty'
    box: 'ubuntu/trusty64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
  - name: 'fail2ban-xenial'
    box: 'ubuntu/xenial64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
