---

- name: 'Install fail2ban packages'
  become: True
  apt:
    name: "{{ item }}"
    state: "{{ fail2ban_package_state }}"
    update_cache: True
    cache_valid_time: 3600
  with_items: "{{ fail2ban_packages }}"
  notify:
    - 'Restart fail2ban'
